// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JirHub.Entities.ViNTD.Models;

public partial class ClassGroup
{
    public int GroupId { get; set; }

    public string GroupName { get; set; }

    public string ProjectCode { get; set; }

    public string SemesterCode { get; set; }

    public int? LecturerId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<GithubCommit> GithubCommits { get; set; } = new List<GithubCommit>();

    public virtual ICollection<GroupMember> GroupMembers { get; set; } = new List<GroupMember>();

    public virtual ICollection<JiraIssue> JiraIssues { get; set; } = new List<JiraIssue>();

    public virtual User Lecturer { get; set; }

    public virtual ProjectConfigsViNtd ProjectConfigsViNtd { get; set; }

    public virtual ICollection<ProjectReport> ProjectReports { get; set; } = new List<ProjectReport>();

    public virtual ICollection<ProjectReposViNtd> ProjectReposViNtds { get; set; } = new List<ProjectReposViNtd>();

    public virtual Semester SemesterCodeNavigation { get; set; }
}