// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace JirHub.Entities.ViNTD.Models;

public partial class PRN222_SE1816_DbContext : DbContext
{
    public PRN222_SE1816_DbContext()
    {
    }

    public PRN222_SE1816_DbContext(DbContextOptions<PRN222_SE1816_DbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ClassGroup> ClassGroups { get; set; }

    public virtual DbSet<GithubCommit> GithubCommits { get; set; }

    public virtual DbSet<GroupMember> GroupMembers { get; set; }

    public virtual DbSet<JiraIssue> JiraIssues { get; set; }

    public virtual DbSet<ProjectConfigsViNtd> ProjectConfigsViNtds { get; set; }

    public virtual DbSet<ProjectReport> ProjectReports { get; set; }

    public virtual DbSet<ProjectReposViNtd> ProjectReposViNtds { get; set; }

    public virtual DbSet<Semester> Semesters { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=LAPTOP-S27O6QTK\\DIEUVI;Initial Catalog=JirHub;Persist Security Info=True;User ID=sa;Password=se181505;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ClassGroup>(entity =>
        {
            entity.HasKey(e => e.GroupId).HasName("PK__class_gr__D57795A04816A2AC");

            entity.ToTable("class_groups");

            entity.HasIndex(e => e.ProjectCode, "UQ__class_gr__891B3A6F6BDB8647").IsUnique();

            entity.Property(e => e.GroupId).HasColumnName("group_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.GroupName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("group_name");
            entity.Property(e => e.LecturerId).HasColumnName("lecturer_id");
            entity.Property(e => e.ProjectCode)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("project_code");
            entity.Property(e => e.SemesterCode)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("semester_code");

            entity.HasOne(d => d.Lecturer).WithMany(p => p.ClassGroups)
                .HasForeignKey(d => d.LecturerId)
                .HasConstraintName("FK_class_groups_lecturer");

            entity.HasOne(d => d.SemesterCodeNavigation).WithMany(p => p.ClassGroups)
                .HasForeignKey(d => d.SemesterCode)
                .HasConstraintName("FK_class_groups_semester");
        });

        modelBuilder.Entity<GithubCommit>(entity =>
        {
            entity.HasKey(e => e.CommitId).HasName("PK__github_c__1C80787332E0408E");

            entity.ToTable("github_commits");

            entity.Property(e => e.CommitId).HasColumnName("commit_id");
            entity.Property(e => e.Additions).HasColumnName("additions");
            entity.Property(e => e.AuthorGithubUsername)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("author_github_username");
            entity.Property(e => e.CommitHash)
                .IsRequired()
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("commit_hash");
            entity.Property(e => e.CommittedDate).HasColumnName("committed_date");
            entity.Property(e => e.Deletions).HasColumnName("deletions");
            entity.Property(e => e.GroupId).HasColumnName("group_id");
            entity.Property(e => e.LinkedIssueKey)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("linked_issue_key");
            entity.Property(e => e.MappedMemberId).HasColumnName("mapped_member_id");
            entity.Property(e => e.Message).HasColumnName("message");

            entity.HasOne(d => d.Group).WithMany(p => p.GithubCommits)
                .HasForeignKey(d => d.GroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_github_commits_group");

            entity.HasOne(d => d.MappedMember).WithMany(p => p.GithubCommits)
                .HasForeignKey(d => d.MappedMemberId)
                .HasConstraintName("FK_github_commits_member");
        });

        modelBuilder.Entity<GroupMember>(entity =>
        {
            entity.HasKey(e => e.MemberId).HasName("PK__group_me__B29B85342F488744");

            entity.ToTable("group_members");

            entity.HasIndex(e => new { e.GroupId, e.UserId }, "UQ_group_user").IsUnique();

            entity.Property(e => e.MemberId).HasColumnName("member_id");
            entity.Property(e => e.GithubUsername)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("github_username");
            entity.Property(e => e.GroupId).HasColumnName("group_id");
            entity.Property(e => e.IsLeader)
                .HasDefaultValue(false)
                .HasColumnName("is_leader");
            entity.Property(e => e.JiraAccountId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("jira_account_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Group).WithMany(p => p.GroupMembers)
                .HasForeignKey(d => d.GroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_group_members_group");

            entity.HasOne(d => d.User).WithMany(p => p.GroupMembers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_group_members_user");
        });

        modelBuilder.Entity<JiraIssue>(entity =>
        {
            entity.HasKey(e => e.IssueId).HasName("PK__jira_iss__D6185C39C897AF3D");

            entity.ToTable("jira_issues");

            entity.HasIndex(e => e.GroupId, "IDX_jira_issues_group");

            entity.HasIndex(e => e.ParentIssueKey, "IDX_jira_issues_parent");

            entity.HasIndex(e => e.Status, "IDX_jira_issues_status");

            entity.Property(e => e.IssueId).HasColumnName("issue_id");
            entity.Property(e => e.AssigneeAccountId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("assignee_account_id");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.GroupId).HasColumnName("group_id");
            entity.Property(e => e.IssueKey)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("issue_key");
            entity.Property(e => e.IssueType)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("issue_type");
            entity.Property(e => e.MappedMemberId).HasColumnName("mapped_member_id");
            entity.Property(e => e.ParentIssueKey)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("parent_issue_key");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.StoryPoints)
                .HasDefaultValue(0.0)
                .HasColumnName("story_points");
            entity.Property(e => e.Summary)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("summary");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");

            entity.HasOne(d => d.Group).WithMany(p => p.JiraIssues)
                .HasForeignKey(d => d.GroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_jira_issues_group");

            entity.HasOne(d => d.MappedMember).WithMany(p => p.JiraIssues)
                .HasForeignKey(d => d.MappedMemberId)
                .HasConstraintName("FK_jira_issues_member");
        });

        modelBuilder.Entity<ProjectConfigsViNtd>(entity =>
        {
            entity.HasKey(e => e.ConfigId).HasName("PK__project___4AD1BFF177B87A76");

            entity.ToTable("project_configs_ViNTD");

            entity.HasIndex(e => e.GroupId, "UQ__project___D57795A190E01226").IsUnique();

            entity.Property(e => e.ConfigId).HasColumnName("config_id");
            entity.Property(e => e.GithubToken).HasColumnName("github_token");
            entity.Property(e => e.GroupId).HasColumnName("group_id");
            entity.Property(e => e.JiraApiToken).HasColumnName("jira_api_token");
            entity.Property(e => e.JiraEmail)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("jira_email");
            entity.Property(e => e.JiraProjectKey)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("jira_project_key");
            entity.Property(e => e.JiraUrl)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("jira_url");

            entity.HasOne(d => d.Group).WithOne(p => p.ProjectConfigsViNtd)
                .HasForeignKey<ProjectConfigsViNtd>(d => d.GroupId)
                .HasConstraintName("FK_project_configs_group");
        });

        modelBuilder.Entity<ProjectReport>(entity =>
        {
            entity.HasKey(e => e.ReportId).HasName("PK__project___779B7C5831BE35E8");

            entity.ToTable("project_reports");

            entity.Property(e => e.ReportId).HasColumnName("report_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.FileUrl)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("file_url");
            entity.Property(e => e.GroupId).HasColumnName("group_id");
            entity.Property(e => e.ReportData).HasColumnName("report_data");
            entity.Property(e => e.ReportType)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("report_type");

            entity.HasOne(d => d.Group).WithMany(p => p.ProjectReports)
                .HasForeignKey(d => d.GroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_project_reports_group");
        });

        modelBuilder.Entity<ProjectReposViNtd>(entity =>
        {
            entity.HasKey(e => e.RepoId).HasName("PK__project___E2D3BC800785EFB5");

            entity.ToTable("project_repos_ViNTD");

            entity.Property(e => e.RepoId).HasColumnName("repo_id");
            entity.Property(e => e.GroupId).HasColumnName("group_id");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.RepoName)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("repo_name");
            entity.Property(e => e.RepoUrl)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("repo_url");

            entity.HasOne(d => d.Group).WithMany(p => p.ProjectReposViNtds)
                .HasForeignKey(d => d.GroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_project_repos_group");
        });

        modelBuilder.Entity<Semester>(entity =>
        {
            entity.HasKey(e => e.SemesterCode).HasName("PK__semester__EC7D418BFDF292DB");

            entity.ToTable("semesters");

            entity.Property(e => e.SemesterCode)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("semester_code");
            entity.Property(e => e.EndDate).HasColumnName("end_date");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.StartDate).HasColumnName("start_date");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__users__B9BE370FC19FCC5D");

            entity.ToTable("users");

            entity.HasIndex(e => e.Email, "UQ__users__AB6E6164DC6B4D7C").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.AvatarUrl)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("avatar_url");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("full_name");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("password_hash");
            entity.Property(e => e.Role).HasColumnName("role");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}