// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JirHub.Entities.ViNTD.Models;

public partial class ProjectReposViNtd
{
    public int RepoId { get; set; }

    public int GroupId { get; set; }

    public string RepoName { get; set; }

    public string RepoUrl { get; set; }

    public bool? IsActive { get; set; }

    public virtual ClassGroup Group { get; set; }
}